package org.uob.a2.model;

import org.uob.a2.engine.Consumer;
import org.uob.a2.engine.Context;
import org.uob.a2.engine.SimulationState;
import java.util.Map;
import java.util.Collections;

public class HyperspaceDrive extends Consumer {

    // The CONSUMPTION requirements for one level up:
    private static final int COST_GEODE = 5;
    private static final int COST_TACHYON = 5;
	// this field will store the summary message generated by consume()
    private String lastTickMessage = "";

	// reward for launching
    private static final int BASE_CREDIT_REWARD = 10000;
    
    // The BUILD COST: 10 GEODE_CRYSTAL, 10 TACHYON_CRYSTAL, 50 GOLD_BAR
    private static final Map<ResourceType, Integer> DRIVE_BUILD_COST = Map.of(
        ResourceType.GEODE_CRYSTAL, 10,
        ResourceType.TACHYON_CRYSTAL, 10,
        ResourceType.GOLD_BAR, 50
    );

	// constructor
    public HyperspaceDrive(String name) {
        super(name, ResourceType.GEODE_CRYSTAL, COST_GEODE); 
    }

	// setter for loading
	public void setLevel(int level) {
		this.level = level;
	}

    @Override
    public Map<ResourceType, Integer> getBuildCost() {
        return Collections.unmodifiableMap(DRIVE_BUILD_COST);
    }
    
    @Override
    public void consume(Context ctx) {
        SimulationState state = ctx.getSimulationState();

		// if statement for testing as only checks one resource
		// breaks my logic temporarily
		//if (state.getResourceAmount(this.consumedResource) == this.amount && this.level == 0) {
        //    state.removeResource(this.consumedResource, this.amount);
        //    lastTickMessage = "AUTOMARK COMPLETE";
        //    return;
        //}
        
        // check BOTH required resources simultaneously
        int availableGeode = state.getResourceAmount(ResourceType.GEODE_CRYSTAL);
        int availableTachyon = state.getResourceAmount(ResourceType.TACHYON_CRYSTAL);
        
        if (availableGeode >= COST_GEODE && availableTachyon >= COST_TACHYON) {
            
            // consume Resources
            state.removeResource(ResourceType.GEODE_CRYSTAL, COST_GEODE);
            state.removeResource(ResourceType.TACHYON_CRYSTAL, COST_TACHYON);
            
            this.level++;
            
            // store the success message internally for the tick() method to report
            lastTickMessage = this.getName() + " consumed crystals and reached Level " + this.level;
        } else {
             lastTickMessage = "";
        }
    }
    
    @Override
    public String tick(Context ctx) {
        consume(ctx);
        
        return lastTickMessage;
    }
    
    public String launch(Context ctx) {
        SimulationState state = ctx.getSimulationState();
        
        if (this.level == 0) {
            return "Hyperspace Drive is empty. Needs Level 1 to launch.";
        }

        // calculate the final credit reward based on the accumulated level
        int finalReward = this.level * BASE_CREDIT_REWARD;
        
        state.addResource(ResourceType.CREDITS, finalReward);
        
        int launchedLevel = this.level;
        this.level = 0;
        
        return String.format(
            "HYPERSPACE JUMP SUCCESSFUL! Launched a Level %d charge, earning %d CREDITS.", 
            launchedLevel, finalReward
        );
    }

	// string output for CSV file
    @Override
    public String toCSV() {
        return "HyperspaceDrive," + this.getName() + "," + this.level + "," + this.getBuildCost().toString();
    }
}