package org.uob.a2.model;

import org.uob.a2.engine.Context;
import org.uob.a2.engine.Converter;
import org.uob.a2.engine.SimulationState;
import java.util.Map;
import java.util.Collections; 

public class RefiningForge extends Converter {

    // Define Conversion Rule: GOLD_ORE (10) -> GOLD_BAR (1)
    private static final int INPUT_AMOUNT = 10;
    private static final int OUTPUT_AMOUNT = 1;
	// this field will store the summary message generated by convert()
    private String lastTickMessage = "";

    // Define Build Cost: 10 LUNAR_STONE
    private static final Map<ResourceType, Integer> REFINING_FORGE_COST = Map.of(
        ResourceType.LUNAR_STONE, 10
    );

	// constructor
    public RefiningForge(String name) {
        super(name, ResourceType.GOLD_ORE, INPUT_AMOUNT, ResourceType.GOLD_BAR, OUTPUT_AMOUNT);
    }

    @Override
    public Map<ResourceType, Integer> getBuildCost() {
        return Collections.unmodifiableMap(REFINING_FORGE_COST);
    }

    @Override
    public String tick(Context ctx) {
        convert(ctx); 
        
        return lastTickMessage;
    }

	@Override
	public void convert(Context ctx) {
		SimulationState state = ctx.getSimulationState();
        
        ResourceType input = this.getInput();
        int inputReq = this.getInputAmount();
        
        // check affordability
        if (state.getResourceAmount(input) >= inputReq) {
            
            state.removeResource(input, inputReq);
            
            state.addResource(this.getOutput(), this.getOutputAmount());
            
            // Store the success message in the field
            lastTickMessage = this.getName() + " converted " + inputReq + " " + input
                   + " to " + this.getOutputAmount() + " " + this.getOutput();
        } else {
             // Store an empty message if conversion did not happen
             lastTickMessage = "";
        }
	}

	// string output for CSV file
	@Override
    public String toCSV() {
        return "RefiningForge," + this.getName() + "," + this.getInput().name() + "," + this.getOutput().name() + "," + this.getInputAmount() + "," + this.getOutputAmount();
    }
}