package org.uob.a2.model;

import org.uob.a2.engine.Context;
import org.uob.a2.engine.Converter;
import org.uob.a2.engine.SimulationState;
import java.util.Map;
import java.util.Collections;

public class TachyonAmplifier extends Converter {

    // Define Conversion Rule: TACHYON_FRAGMENT (10) -> TACHYON_CRYSTAL (1)
    private static final int INPUT_AMOUNT_FRAGMENTS = 10;
    private static final int OUTPUT_AMOUNT_CRYSTALS = 1;
	// this field will store the summary message generated by convert()
    private String lastTickMessage = "";

    // Define Build Cost: 1 GEODE_CRYSTAL and 1 GOLD_BAR
    private static final Map<ResourceType, Integer> AMPLIFIER_BUILD_COST = Map.of(
        ResourceType.GEODE_CRYSTAL, 1,
        ResourceType.GOLD_BAR, 1
    );
    
    // Define the map of resources required for conversion as 2 resources required
    private static final Map<ResourceType, Integer> CONVERSION_INPUT = Map.of(
        ResourceType.TACHYON_FRAGMENT, 10
    );


	// constructor
    public TachyonAmplifier(String name) {
        super(name, ResourceType.TACHYON_FRAGMENT, INPUT_AMOUNT_FRAGMENTS, ResourceType.TACHYON_CRYSTAL, OUTPUT_AMOUNT_CRYSTALS);
    }

    @Override
    public Map<ResourceType, Integer> getBuildCost() {
        return Collections.unmodifiableMap(AMPLIFIER_BUILD_COST);
    }

    @Override
    public String tick(Context ctx) {
		convert(ctx); 
        
        return lastTickMessage;
    }

	@Override
	public void convert(Context ctx) {
		SimulationState state = ctx.getSimulationState();
        
        ResourceType input = this.getInput();
        int inputReq = this.getInputAmount();
        
        // check affordability
        if (state.getResourceAmount(input) >= inputReq) {
            
            state.removeResource(input, inputReq);
            
            state.addResource(this.getOutput(), this.getOutputAmount());
            
            // Store the success message in the field
            lastTickMessage = this.getName() + " converted " + inputReq + " " + input
                   + " to " + this.getOutputAmount() + " " + this.getOutput();
        } else {
             // Store an empty message if conversion did not happen
             lastTickMessage = "";
		}
	}

	// string output for CSV file
	@Override
    public String toCSV() {
        return "TachyonAmplifier," + this.getName() + "," + this.getInput().name() + "," + this.getOutput().name() + "," + this.getInputAmount() + "," + this.getOutputAmount();
    }
}